name: flutter_application_note
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  msh_checkbox: ^1.1.1
  time_pickerr: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
 


  flutter_lints: ^2.0.0





flutter:


  uses-material-design: true


  assets:
    - assets/images/







  fonts:
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500
    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 700
          

